version: "3.7"

services:
  hb_project-web:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    container_name: hb_project-web_1
    command: bin/start
    ports:
    - 127.0.0.1:3005:3005