#!/bin/bash

if docker-compose exec -T hb_project-web echo "Running in existing hb_project-web container ..." 2>/dev/null
then
  run_or_exec="exec"
else
  run_or_exec="run --rm"
fi

docker-compose $run_or_exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" hb_project-web bash -c "$*"